language: go
go:
  - 1.6.2
  - 1.7.3
before_install:
  - go get golang.org/x/tools/cmd/cover github.com/golang/lint/golint
install:
  - ./install_ci.sh
after_success:
  - make coverdata
  - bash <(curl -s https://codecov.io/bash)
script:
  - make -j4 check GOTEST_FLAGS=-v
