language: go
go:
  - 1.7.x
  - 1.8.x
  - tip
before_install:
  - go get golang.org/x/tools/cmd/cover github.com/golang/lint/golint
  - >
    wget -nv http://apache.claz.org/hbase/1.2.5/hbase-1.2.5-bin.tar.gz &&
    echo "A7E5124BF082E87839DD99DE846EDB8A  hbase-1.2.5-bin.tar.gz" | md5sum --strict --check - &&
    tar zxf hbase-1.2.5-bin.tar.gz --exclude=docs &&
    ln -s hbase-1.2.5 hbase
install:
  - ./install_ci.sh
after_success:
  - make coverdata
  - bash <(curl -s https://codecov.io/bash)
before_script:
  - hbase/bin/hbase-daemon.sh --config hbase/conf start master
script:
  - make -j4 jenkins GOTEST_FLAGS=-v
